### ISSUE TITLE
Как использовать ваше творение?

### ISSUE THREAD

**Issue by alekseyruzov** [leonaded/sketch-backup#1]
Не вижу документации

**Comment by leonaded** [comment]
А это на самом деле личный репозиторий для личного использования :) но можно его клонировать, забэкапить настройки через sync.sh и залить в свой репозиторий

**Comment by alekseyruzov** [comment]
Ну раз такое дело, можно разъяснить как работает ваш код? Я правильно понимаю, что бекапятся все настройки и плагины скетча? Как это сделать, если да?

**Comment by leonaded** [comment]
Да, это простой bash-скрипт, который копирует все настройки и плагины скетча в папку `~/sketch-backup`, и наоборот.
Чтобы экспортировать настройки и плагины в папку, нужно запустить скрипт с параметром `-u`, а чтобы импортировать настройки и плагины обратно, нужно запустить скрипт с параметром `-g`.
